import type { ServiceData } from './servicesData';

export const servicesDataEn: ServiceData[] = [
  {
    slug: 'ucotun-diaqnostikasi-ve-berpasi',
    index: '01',
    name: 'Accounting Diagnostics and Restoration',
    tagline: 'The first step to financial health',
    heroDescription: 'Professional support for the comprehensive review and restoration of your company\'s accounting and tax records.',
    overview: 'Professional support for the comprehensive review and restoration of your company\'s accounting and tax records.',
    highlights: [
      'Complete clarity on the true state of your records',
      'Prior-period errors identified and corrected',
      'Financial statements you can rely on',
      'Fully restored accounting data',
      'A clear accounting policy roadmap for the future',
    ],
    iconName: 'ScanSearch',
    features: [
      { title: 'Verification of the correctness of bookkeeping', description: 'A comprehensive analysis of every aspect of your existing accounting system; full compatibility with 1C and other widely used platforms is ensured.' },
      { title: 'Identification of errors from previous periods', description: 'Discrepancies and errors in prior-period financial records are identified with precision and catalogued.' },
      { title: 'Verification of the accuracy of financial statements', description: 'Statements are checked against the company\'s true financial position; deviations are documented.' },
      { title: 'Restoration of accounting data', description: 'Missing or incorrectly maintained accounting data is reinstated in the correct format.' },
      { title: 'Preparation of recommendations on accounting policy', description: 'A detailed recommendations document is prepared for your company to prevent the same errors recurring in future.' },
    ],
    targets: ['Newly established companies', 'Businesses with disrupted records', 'Companies preparing for audit', 'Enterprises undergoing ownership changes'],
    process: [
      { step: '01', title: 'Enquiry & briefing', description: 'Initial information about your company is gathered and problem areas are discussed.' },
      { step: '02', title: 'Document analysis', description: 'Existing accounting records, reports and systems are reviewed in detail.' },
      { step: '03', title: 'Full diagnostics', description: 'Every accounting element is examined with precision; errors are catalogued.' },
      { step: '04', title: 'Recovery & reporting', description: 'Errors are corrected, and a full diagnostics report along with a recommendations package is delivered.' },
    ],
    relatedSlugs: ['muhasibat-konsaltinqi', 'auditor-xidmetleri', 'vergi-konsaltinqi'],
  },
  {
    slug: 'muhasibat-konsaltinqi',
    index: '02',
    name: 'Accounting Consulting',
    tagline: 'Reliable support behind the numbers',
    heroDescription: 'Full organisation and professional support of your company\'s accounting.',
    overview: 'Full organisation and professional support of your company\'s accounting.',
    highlights: [
      'Company infrastructure ready, from registration to bookkeeping',
      'A working accounting system built from the ground up',
      'Full accounting support without an in-house accountant',
      'Automated processes free of manual effort',
      'Financial statements ready for banks and investors',
    ],
    iconName: 'Calculator',
    features: [
      { title: 'Registration and accounting support for new companies', description: 'Guidance at every stage, from company registration to the first working accounting system.' },
      { title: 'Set-up and implementation of the accounting system', description: 'An accounting system and policy tailored to your company\'s structure is developed and implemented.' },
      { title: 'Accounting outsourcing', description: 'Day-to-day transaction recording and the full accounting function are handled by our team.' },
      { title: 'Accounting automation', description: 'Accounting processes are automated on 1C and cloud solutions — we fully adapt to your existing software.' },
      { title: 'Preparation of financial statements', description: 'Monthly, quarterly and annual statements prepared for external users — banks, investors and partners.' },
    ],
    targets: ['Small and medium-sized businesses', 'Start-ups', 'Branches of international companies', 'Entrepreneurs'],
    process: [
      { step: '01', title: 'Business analysis', description: 'Your company\'s operations, transaction volume and existing accounting system are reviewed.' },
      { step: '02', title: 'System setup', description: 'The most appropriate accounting system and policy is developed for you.' },
      { step: '03', title: 'Ongoing service', description: 'Daily transactions are recorded; monthly reports are prepared.' },
      { step: '04', title: 'Reporting & analysis', description: 'Financial results are interpreted and decision-making is supported.' },
    ],
    relatedSlugs: ['ucotun-diaqnostikasi-ve-berpasi', 'vergi-konsaltinqi', 'maliyye-ve-idareetme-konsaltinqi'],
  },
  {
    slug: 'vergi-konsaltinqi',
    index: '03',
    name: 'Tax Consulting',
    tagline: 'Legal optimization, maximum savings',
    heroDescription: 'Professional support on tax legislation matters.',
    overview: 'Professional support on tax legislation matters.',
    highlights: [
      'A ready tax strategy aligned with your business',
      'A lawfully reduced tax burden',
      'Predictable tax liabilities',
      'Accurate returns filed on time',
      'Always ahead of legislative changes',
    ],
    iconName: 'FileText',
    features: [
      { title: 'Development of tax strategy', description: 'The most advantageous tax regime for your activities is selected and a long-term tax strategy is built.' },
      { title: 'Optimisation of the tax burden', description: 'VAT optimisation, expense recognition and relief mechanisms are applied within the legal framework to minimise the tax burden.' },
      { title: 'Tax planning', description: 'Tax liabilities are forecast in advance — unexpected amounts and penalty risks are ruled out.' },
      { title: 'Preparation of tax reports', description: 'Returns are prepared and submitted via the government\'s electronic system at least 5–7 business days before the deadline.' },
      { title: 'Advice on changes in tax legislation', description: 'Every change in the Tax Code is tracked, with proactive advice on its impact on your business.' },
    ],
    targets: ['Manufacturing enterprises', 'Trading companies', 'Service sector businesses', 'Foreign investors'],
    process: [
      { step: '01', title: 'Tax audit', description: 'The current tax position is fully analysed and risks are identified.' },
      { step: '02', title: 'Strategy', description: 'A lawful tax optimisation strategy is developed.' },
      { step: '03', title: 'Implementation', description: 'The strategy is put into effect and returns are prepared.' },
      { step: '04', title: 'Monitoring', description: 'Tax obligations are continuously monitored for compliance.' },
    ],
    relatedSlugs: ['muhasibat-konsaltinqi', 'auditor-xidmetleri', 'maliyye-ve-idareetme-konsaltinqi'],
  },
  {
    slug: 'maliyye-ve-idareetme-konsaltinqi',
    index: '04',
    name: 'Financial and Management Consulting',
    tagline: 'From strategy to results',
    heroDescription: 'Professional support for developing your company\'s financial management system.',
    overview: 'Professional support for developing your company\'s financial management system.',
    highlights: [
      'A complete diagnostic picture of your finances',
      'Management driven by numbers, not intuition',
      'Ready financial models across scenarios',
      'A clear budget and financial plan',
      'Operational dashboards for leadership',
    ],
    iconName: 'BarChart3',
    features: [
      { title: 'Financial diagnostics of the business', description: 'The company\'s financial position is analysed in depth; strengths and weaknesses are identified.' },
      { title: 'Set-up and implementation of management accounting', description: 'A management accounting system with KPI indicators is built to support leadership decision-making.' },
      { title: 'Financial modelling', description: 'Dynamic financial models are built across scenarios — with NPV, IRR and payback period calculated.' },
      { title: 'Financial planning', description: 'The annual budget is prepared, revenues and expenses are forecast, and variance controls are put in place.' },
      { title: 'Preparation of management reports', description: 'Operational reports for internal users in Excel, Power BI and Google Sheets dashboard formats.' },
    ],
    targets: ['Medium and large enterprises', 'Holding companies', 'Investment-seeking businesses', 'Rapidly growing companies'],
    process: [
      { step: '01', title: 'Situation analysis', description: 'The current financial position, processes and objectives are examined.' },
      { step: '02', title: 'Model construction', description: 'Financial models and a budget framework are developed.' },
      { step: '03', title: 'Strategy', description: 'A financial strategy aligned with the objectives is formulated.' },
      { step: '04', title: 'Implementation & monitoring', description: 'The strategy is implemented and results are systematically tracked.' },
    ],
    relatedSlugs: ['vergi-konsaltinqi', 'muhasibat-konsaltinqi', 'auditor-xidmetleri'],
  },
  {
    slug: 'emeliyyat-ve-reqemsal-konsaltinq',
    index: '05',
    name: 'Operational and Digital Consulting',
    tagline: 'We digitise your business',
    heroDescription: 'Professional support in optimising processes and adopting modern technologies to increase business efficiency.',
    overview: 'Professional support in optimising processes and adopting modern technologies to increase business efficiency.',
    highlights: [
      'Transparent, fully mapped business processes',
      'Documented standard operating procedures',
      'A working ERP/CRM system and a trained team',
      'Automated processes free of manual effort',
      'Reduced operating costs with measurable savings',
    ],
    iconName: 'Monitor',
    features: [
      { title: 'Business process modelling', description: 'Existing workflows are mapped; bottlenecks and duplicated operations are uncovered.' },
      { title: 'Development of standard operating procedures', description: 'Clear procedure documents are prepared for every process — work depends on the system, not on individuals.' },
      { title: 'Implementation of ERP and CRM systems', description: 'The right system is independently evaluated and selected for your needs; implementation, data migration and API integration follow.' },
      { title: 'Process automation', description: 'Manual operations are migrated to automated systems, and employees are trained on them.' },
      { title: 'Optimisation of operating costs', description: 'Inefficient cost sources are identified and an optimisation plan is delivered with an ROI calculation.' },
    ],
    targets: ['Manufacturing companies', 'Trading enterprises', 'Service companies', 'Businesses seeking digital transformation'],
    process: [
      { step: '01', title: 'Process mapping', description: 'Existing business processes are mapped and problems are identified.' },
      { step: '02', title: 'Solution design', description: 'The optimal digital solution is selected and a project plan is prepared.' },
      { step: '03', title: 'Implementation', description: 'The system is configured, data is migrated and testing is conducted.' },
      { step: '04', title: 'Support', description: 'Staff are trained and ongoing technical support is provided.' },
    ],
    relatedSlugs: ['muhasibat-konsaltinqi', 'hr-ve-kadrlar-konsaltinqi', 'maliyye-ve-idareetme-konsaltinqi'],
  },
  {
    slug: 'hr-ve-kadrlar-konsaltinqi',
    index: '06',
    name: 'HR and Personnel Consulting',
    tagline: 'People at the centre',
    heroDescription: 'Set-up and professional support of your company\'s HR system.',
    overview: 'Set-up and professional support of your company\'s HR system.',
    highlights: [
      'Personnel documentation in full legal compliance',
      'Payroll calculated accurately and on time',
      'Working HR policies tailored to your company',
      'The right people, properly recruited and onboarded',
      'A business protected from labour disputes',
    ],
    iconName: 'Users',
    features: [
      { title: 'HR record-keeping', description: 'All personnel documentation — employment contracts, orders, service records and reports to the State Social Protection Fund (DSMF) — is maintained in compliance with the Labour Code.' },
      { title: 'Payroll calculation', description: 'Salary, leave and social insurance calculations are performed accurately and on time.' },
      { title: 'Development of HR policies', description: 'Internal rules of procedure, job descriptions and motivation mechanisms are prepared to fit your company\'s structure.' },
      { title: 'Personnel selection and recruitment', description: 'Recruitment, onboarding and performance appraisal processes are established systematically.' },
      { title: 'Support in line with labour legislation', description: 'Changes in the Labour Code are monitored, with professional support in the lawful resolution of disputes.' },
    ],
    targets: ['Growing companies', 'Enterprises with large workforces', 'Branches of foreign companies', 'Companies seeking to build an HR department'],
    process: [
      { step: '01', title: 'HR audit', description: 'Existing HR processes, documentation and systems are reviewed.' },
      { step: '02', title: 'System design', description: 'An HR system tailored to the company\'s needs is designed.' },
      { step: '03', title: 'Implementation', description: 'Documents are prepared and processes are put in place.' },
      { step: '04', title: 'Ongoing support', description: 'Changes in labour legislation are monitored and the system is kept up to date.' },
    ],
    relatedSlugs: ['telim-ve-inkisaf', 'emeliyyat-ve-reqemsal-konsaltinq', 'muhasibat-konsaltinqi'],
  },
  {
    slug: 'telim-ve-inkisaf',
    index: '07',
    name: 'Training and Development',
    tagline: 'Knowledge becomes power',
    heroDescription: 'Professional support in developing employees\' skills and management competencies.',
    overview: 'Professional support in developing employees\' skills and management competencies.',
    highlights: [
      'A clear picture of your team\'s real knowledge level',
      'A training programme built around your needs',
      'Employees with hands-on practical skills',
      'Certified accounting and HR specialists',
    ],
    iconName: 'GraduationCap',
    features: [
      { title: 'Employee assessment', description: 'The team\'s knowledge level and development needs are identified through objective methods.' },
      { title: 'Development of training programmes', description: 'Bespoke learning programmes in individual and group formats, based on a needs analysis.' },
      { title: 'Delivery of professional trainings', description: 'Practical, interactive sessions grounded in real business scenarios — including online modules with a personal learning dashboard.' },
      { title: 'Training of accounting and HR specialists', description: 'Specialised programmes for accounting, tax and HR professionals — an official certificate is awarded on successful completion.' },
    ],
    targets: ['Finance professionals', 'Accountants', 'Company managers', 'Those seeking to advance their careers'],
    process: [
      { step: '01', title: 'Needs analysis', description: 'Your level of knowledge and learning objectives are identified.' },
      { step: '02', title: 'Programme design', description: 'A learning programme specifically designed for you is prepared.' },
      { step: '03', title: 'Training process', description: 'Practically oriented, interactive training sessions are delivered.' },
      { step: '04', title: 'Assessment', description: 'Knowledge acquisition is evaluated and a certificate is awarded.' },
    ],
    relatedSlugs: ['hr-ve-kadrlar-konsaltinqi', 'muhasibat-konsaltinqi', 'vergi-konsaltinqi'],
  },
  {
    slug: 'auditor-xidmetleri',
    index: '08',
    name: 'Audit Services',
    tagline: 'Independent review, precise results',
    heroDescription: 'Professional support for the independent assessment of your company\'s financial and operational processes.',
    overview: 'Professional support for the independent assessment of your company\'s financial and operational processes.',
    highlights: [
      'An independent, objective view of your processes',
      'Confirmed compliance with legislation',
      'A strengthened internal control system',
      'Risks uncovered, with a clear action plan',
    ],
    iconName: 'ShieldCheck',
    features: [
      { title: 'Internal audit', description: 'Independent assessment of the company\'s internal processes and management effectiveness, conducted in accordance with ISA (International Standards on Auditing).' },
      { title: 'Compliance audit', description: 'Comprehensive review of compliance with legislative requirements; identified gaps are documented.' },
      { title: 'Analysis of the internal control system', description: 'The effectiveness of control mechanisms is evaluated, with recommendations on weak points.' },
      { title: 'Identification of financial and operational risks', description: 'Business risks are identified; a detailed audit report and management letter are delivered.' },
    ],
    targets: ['Medium and large enterprises', 'Banks and financial institutions', 'State-owned enterprises', 'Foreign investors'],
    process: [
      { step: '01', title: 'Planning', description: 'The audit scope is defined and risk areas are identified.' },
      { step: '02', title: 'Document collection', description: 'Financial documents, reports and internal processes are analysed.' },
      { step: '03', title: 'Fieldwork', description: 'Audit procedures are carried out and evidence is gathered.' },
      { step: '04', title: 'Reporting', description: 'The audit report is prepared and presented to management.' },
    ],
    relatedSlugs: ['ucotun-diaqnostikasi-ve-berpasi', 'vergi-konsaltinqi', 'maliyye-ve-idareetme-konsaltinqi'],
  },
];

export function getServiceEnBySlug(slug: string): ServiceData | undefined {
  return servicesDataEn.find(s => s.slug === slug);
}
